home: '/hpcscratch/user/kiliakis/'
blond_home: '/hpcscratch/user/kiliakis/git/BLonD-mpi/'
exe_home: '/hpcscratch/user/kiliakis/git/BLonD-mpi/__EXAMPLES/main_files/'
batch_script: '/hpcscratch/user/kiliakis/git/BLonD-mpi/scripts/other/batch-simple.sh'
batch_setup: '/hpcscratch/user/kiliakis/git/BLonD-mpi/scripts/other/batch-setup.sh'
blond_repos: '/hpcscratch/user/kiliakis/git/blond_repos/'
result_dir: '/hpcscratch/user/kiliakis/git/BLonD-mpi/results/raw/'
mpi_versions:
    openmpi3:
        module_name: 'mpi/openmpi/3.0.0'
        path: '/hpcscratch/user/kiliakis/install/miniconda3-openmpi3.0.0/bin/'
    mvapich2:
        module_name: 'mpi/mvapich/2.3'
        path: '/hpcscratch/user/kiliakis/install/miniconda3-mvapich2.3/bin/'
    mpich3:
        module_name: 'mpi/mpich/3.2.1'
        path: '/hpcscratch/user/kiliakis/install/anaconda3/bin/'