####################
#
# Simple HTCondor submit description file
# Everything with a leading # is a comment
####################




# +MaxRuntime = 60
#request_memory = 1024

# executable 		= condor.sh
# arguments    	= "python --version"
# output       	= output.$(ClusterId)
# error        	= error.$(ClusterId)
# log          	= log.$(ClusterId)
# request_cpus   	= 1
# getenv 			= True
# +MaxRuntime 	= 3600
# should_transfer_files = IF_NEEDED
queue
